### ISSUE TITLE
TES3MP

### ISSUE THREAD

**Issue by killertobyd** [HotaruBlaze/TES3MP-Egg#1]
![Unbenannt](https://user-images.githubusercontent.com/96026375/205161725-8804a3ba-8fa6-4cb2-9810-0bc628f0a943.PNG)

since the latest update of TES3MP the folder is empty when downloading

**Comment by HotaruBlaze** [comment]
Wow, I never got a notification for this, going to close it for now but if you need help with this again, just reopen it, sorry for never replying
